theme: jekyll-theme-cayman
title: Code Reengineering
description: Code Reengineering - Smell, Refactoring, and Technical Debts.
plugins:
  - jemoji

defaults:
  -
    values:
      layout: "content"
      big_header: false
